name: wiki-quality
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - scikit-learn=1.0.2
  - pip:
    - autopep8==1.6.0
    - numpy==1.18.5
    - protobuf==3.20.0
    - streamlit==1.9.0
    - xgboost==1.2.1