name: wiki-quality
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.3.1
  - notebook=6.1.4
  - numpy-base=1.19.2
  - pandas=1.1.3
  - pickleshare=0.7.5
  - pip=20.2.3
  - plotly=4.11.0
  - python=3.8.5
  - scikit-learn=1.0.2
  - scipy=1.5.0
  - seaborn=0.11.0
  - pip:
    - autopep8==1.6.0
    - numpy==1.18.5
    - protobuf==3.20.0
    - streamlit==1.9.0
    - xgboost==1.2.1